// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_scanner.proto

package com.coderalliance.apimaster.service.rpc;

public final class ApiScanner {
  private ApiScanner() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScanApiRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.coderalliance.apimaster.service.rpc.ScanApiRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 project_id = 1;</code>
     * @return The projectId.
     */
    long getProjectId();

    /**
     * <code>string git_address = 2;</code>
     * @return The gitAddress.
     */
    java.lang.String getGitAddress();
    /**
     * <code>string git_address = 2;</code>
     * @return The bytes for gitAddress.
     */
    com.google.protobuf.ByteString
        getGitAddressBytes();

    /**
     * <code>string git_branch = 3;</code>
     * @return The gitBranch.
     */
    java.lang.String getGitBranch();
    /**
     * <code>string git_branch = 3;</code>
     * @return The bytes for gitBranch.
     */
    com.google.protobuf.ByteString
        getGitBranchBytes();
  }
  /**
   * Protobuf type {@code com.coderalliance.apimaster.service.rpc.ScanApiRequest}
   */
  public static final class ScanApiRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.coderalliance.apimaster.service.rpc.ScanApiRequest)
      ScanApiRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScanApiRequest.newBuilder() to construct.
    private ScanApiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanApiRequest() {
      gitAddress_ = "";
      gitBranch_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScanApiRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.class, com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.Builder.class);
    }

    public static final int PROJECT_ID_FIELD_NUMBER = 1;
    private long projectId_ = 0L;
    /**
     * <code>int64 project_id = 1;</code>
     * @return The projectId.
     */
    @java.lang.Override
    public long getProjectId() {
      return projectId_;
    }

    public static final int GIT_ADDRESS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gitAddress_ = "";
    /**
     * <code>string git_address = 2;</code>
     * @return The gitAddress.
     */
    @java.lang.Override
    public java.lang.String getGitAddress() {
      java.lang.Object ref = gitAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string git_address = 2;</code>
     * @return The bytes for gitAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGitAddressBytes() {
      java.lang.Object ref = gitAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GIT_BRANCH_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gitBranch_ = "";
    /**
     * <code>string git_branch = 3;</code>
     * @return The gitBranch.
     */
    @java.lang.Override
    public java.lang.String getGitBranch() {
      java.lang.Object ref = gitBranch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gitBranch_ = s;
        return s;
      }
    }
    /**
     * <code>string git_branch = 3;</code>
     * @return The bytes for gitBranch.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGitBranchBytes() {
      java.lang.Object ref = gitBranch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gitBranch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (projectId_ != 0L) {
        output.writeInt64(1, projectId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gitAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gitAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gitBranch_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gitBranch_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (projectId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, projectId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gitAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gitAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gitBranch_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gitBranch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest)) {
        return super.equals(obj);
      }
      com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest other = (com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest) obj;

      if (getProjectId()
          != other.getProjectId()) return false;
      if (!getGitAddress()
          .equals(other.getGitAddress())) return false;
      if (!getGitBranch()
          .equals(other.getGitBranch())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProjectId());
      hash = (37 * hash) + GIT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getGitAddress().hashCode();
      hash = (37 * hash) + GIT_BRANCH_FIELD_NUMBER;
      hash = (53 * hash) + getGitBranch().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.coderalliance.apimaster.service.rpc.ScanApiRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.coderalliance.apimaster.service.rpc.ScanApiRequest)
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.class, com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.Builder.class);
      }

      // Construct using com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        projectId_ = 0L;
        gitAddress_ = "";
        gitBranch_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor;
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest getDefaultInstanceForType() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest build() {
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest buildPartial() {
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest result = new com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.projectId_ = projectId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gitAddress_ = gitAddress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.gitBranch_ = gitBranch_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest) {
          return mergeFrom((com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest other) {
        if (other == com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest.getDefaultInstance()) return this;
        if (other.getProjectId() != 0L) {
          setProjectId(other.getProjectId());
        }
        if (!other.getGitAddress().isEmpty()) {
          gitAddress_ = other.gitAddress_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getGitBranch().isEmpty()) {
          gitBranch_ = other.gitBranch_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                projectId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                gitAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                gitBranch_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long projectId_ ;
      /**
       * <code>int64 project_id = 1;</code>
       * @return The projectId.
       */
      @java.lang.Override
      public long getProjectId() {
        return projectId_;
      }
      /**
       * <code>int64 project_id = 1;</code>
       * @param value The projectId to set.
       * @return This builder for chaining.
       */
      public Builder setProjectId(long value) {

        projectId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 project_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProjectId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        projectId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object gitAddress_ = "";
      /**
       * <code>string git_address = 2;</code>
       * @return The gitAddress.
       */
      public java.lang.String getGitAddress() {
        java.lang.Object ref = gitAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string git_address = 2;</code>
       * @return The bytes for gitAddress.
       */
      public com.google.protobuf.ByteString
          getGitAddressBytes() {
        java.lang.Object ref = gitAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string git_address = 2;</code>
       * @param value The gitAddress to set.
       * @return This builder for chaining.
       */
      public Builder setGitAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gitAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string git_address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGitAddress() {
        gitAddress_ = getDefaultInstance().getGitAddress();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string git_address = 2;</code>
       * @param value The bytes for gitAddress to set.
       * @return This builder for chaining.
       */
      public Builder setGitAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gitAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object gitBranch_ = "";
      /**
       * <code>string git_branch = 3;</code>
       * @return The gitBranch.
       */
      public java.lang.String getGitBranch() {
        java.lang.Object ref = gitBranch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gitBranch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string git_branch = 3;</code>
       * @return The bytes for gitBranch.
       */
      public com.google.protobuf.ByteString
          getGitBranchBytes() {
        java.lang.Object ref = gitBranch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gitBranch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string git_branch = 3;</code>
       * @param value The gitBranch to set.
       * @return This builder for chaining.
       */
      public Builder setGitBranch(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gitBranch_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string git_branch = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGitBranch() {
        gitBranch_ = getDefaultInstance().getGitBranch();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string git_branch = 3;</code>
       * @param value The bytes for gitBranch to set.
       * @return This builder for chaining.
       */
      public Builder setGitBranchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gitBranch_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.coderalliance.apimaster.service.rpc.ScanApiRequest)
    }

    // @@protoc_insertion_point(class_scope:com.coderalliance.apimaster.service.rpc.ScanApiRequest)
    private static final com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest();
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScanApiRequest>
        PARSER = new com.google.protobuf.AbstractParser<ScanApiRequest>() {
      @java.lang.Override
      public ScanApiRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ScanApiRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanApiRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScanApiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.coderalliance.apimaster.service.rpc.ScanApiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.coderalliance.apimaster.service.rpc.ScanApiResponse}
   */
  public static final class ScanApiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.coderalliance.apimaster.service.rpc.ScanApiResponse)
      ScanApiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScanApiResponse.newBuilder() to construct.
    private ScanApiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanApiResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScanApiResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.class, com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse)) {
        return super.equals(obj);
      }
      com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse other = (com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.coderalliance.apimaster.service.rpc.ScanApiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.coderalliance.apimaster.service.rpc.ScanApiResponse)
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.class, com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.Builder.class);
      }

      // Construct using com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor;
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse getDefaultInstanceForType() {
        return com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse build() {
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse buildPartial() {
        com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse result = new com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse) {
          return mergeFrom((com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse other) {
        if (other == com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.coderalliance.apimaster.service.rpc.ScanApiResponse)
    }

    // @@protoc_insertion_point(class_scope:com.coderalliance.apimaster.service.rpc.ScanApiResponse)
    private static final com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse();
    }

    public static com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScanApiResponse>
        PARSER = new com.google.protobuf.AbstractParser<ScanApiResponse>() {
      @java.lang.Override
      public ScanApiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ScanApiResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanApiResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.coderalliance.apimaster.service.rpc.ApiScanner.ScanApiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021api_scanner.proto\022\'com.coderalliance.a" +
      "pimaster.service.rpc\"M\n\016ScanApiRequest\022\022" +
      "\n\nproject_id\030\001 \001(\003\022\023\n\013git_address\030\002 \001(\t\022" +
      "\022\n\ngit_branch\030\003 \001(\t\"3\n\017ScanApiResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\213\001\n\016Sca" +
      "nApiService\022y\n\004Scan\0227.com.coderalliance." +
      "apimaster.service.rpc.ScanApiRequest\0328.c" +
      "om.coderalliance.apimaster.service.rpc.S" +
      "canApiResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_coderalliance_apimaster_service_rpc_ScanApiRequest_descriptor,
        new java.lang.String[] { "ProjectId", "GitAddress", "GitBranch", });
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_coderalliance_apimaster_service_rpc_ScanApiResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
